# Generated by Django 5.0.1 on 2024-03-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='missingUsername', max_length=40),
            preserve_default=False,
        ),
    ]
