# Generated by Django 5.0.1 on 2024-03-07 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerBackend', '0005_game_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='game',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='is_completed',
        ),
        migrations.CreateModel(
            name='GameLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
