# Generated by Django 5.0.1 on 2024-03-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerBackend', '0006_remove_challenge_game_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='GameLobby',
        ),
    ]
