# Generated by Django 5.0.1 on 2024-03-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerBackend', '0005_user_is_staff_alter_user_is_superuser'),
        ('ServerBackend', '0009_game_participant_response_task_delete_admin_and_more'),
    ]

    operations = [
    ]
